parameters:
- name: environment
  type: string
  displayName: 'The environment name'

- name: serviceConnectionApp
  type: string
  displayName: 'The Service Connection to run Terraform'

- name: dependsOn
  type: string
  displayName: 'The components this job depends on like another job'
  default: ''

jobs:
- deployment: ${{ parameters.environment }}
  dependsOn: ${{ parameters.dependsOn }}
  displayName: Deploy
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          clean: true
        - template: ../PipelineTemplates/Terraform/Terraform.yaml
          parameters:
            serviceConnectionApp: ${{ parameters.serviceConnectionApp }}
            environment: ${{ parameters.environment }}



